config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'
  get     'help'    =>  'static_pages#help'
  get     'about'   =>  'static_pages#about'
  get     'contact' =>  'static_pages#contact'
  get     'signup'  =>  'users#new'

  get     'login'   =>  'sessions#new'
  post    'login'   =>  'sessions#create'
  delete  'logout'  =>  'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  #----------------------------------------------------------------------------
  # Public methods (actions)
  #----------------------------------------------------------------------------

  def home
    # Returns micropost object and feed items to populate home view.
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_landing_page.html.erb
<% provide(:title, "Home" ) %>

<!-- Slider Section -->
<div class="slider">
  <!-- Slide 1 -->
  <div class="slide active-slide" id="slide-1">
    <div class="container">
      <div class="row">
        <div class="slide-copy col-xs-6">
          <h1>Rails Social Networking App</h1>
          <p>
            This is a sample social networking site developed with Ruby 2 and 
            Rails 4. <br/>It replaces an earlier version of 
            <a href="http://www.twitter.com/" target="_blank">Twitter</a> 
            with all features built from scratch.
          </p>
          <a class="btn btn-lg btn-danger" href="<%= signup_path %>">
            <span class="glyphicon glyphicon-pencil"></span>
            Sign up now!
          </a>
        </div>
        <div class="slide-img col-xs-6">
        </div>
      </div>
    </div>      
  </div>
  <!-- Slide 2 -->
  <div class="slide" id="slide-2">
    <div class="container">
      <div class="row">
        <div class="slide-copy col-xs-12">
          <h1>Relevant Features</h1>
          <p>
            User profiles, microposts with images, and personal status feeds included.
          </p>
          <p>
            <a href="<%= about_path %>" class="action-link">
              <span class="glyphicon glyphicon-heart"></span>
              View features
            </a>
          </p>
        </div>
      </div>
    </div>      
  </div> 
  <!-- Slide 3 -->
  <div class="slide" id="slide-3">
    <div class="container">
      <div class="row">
        <div class="slide-copy col-xs-12">
          <h1>Technologies and Languages</h1>
          <p>
            MVC software architecture, well-documented Ruby code, and Amazon 
            Web Services behind the scenes.
          </p>
          <p>
            <a href="<%= about_path %>" class="action-link">
              <span class="glyphicon glyphicon-cog"></span>
              Learn more
            </a>
          </p>
        </div>
      </div>
    </div>      
  </div> 
</div>
<!-- Slider nav section -->
<div class="slider-nav">
  <a href="#" class="arrow-prev"></a>
  <ul class="slider-dots">
    <li class="dot active-dot">&bull;</li>
    <li class="dot">&bull;</li>
    <li class="dot">&bull;</li>
  </ul>
  <a href="#" class="arrow-next"></a>
</div> 
<!-- Features section -->
<div class="container">
  <div class="row">
    <div class="col-md-12 center">
      <h3>A Simple Yet Robust and Extensible Application</h3>
      <p>
        These are some of the features of this sample social networking app 
        built with Ruby 2 and Rails 4. <a href="<%= about_path %>">Learn more.</a>
      </p>
    </div>
  </div>
</div>
<div class="feature feature-back">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="feature-1" title="Ruby on Rails Backend"></div>
        </div>
      </div>
      <div class="col-md-6">
        <h2>
          <span class="glyphicon glyphicon-road"></span>&nbsp;
          Ruby on Rails Backend
        </h2>
        <p>
          This website benefits from Rails principles such as convention over
          configuration, don't repeat yourself (DRY) and the REST architectural
          style for structuring web applications. <a href="http://rubyonrails.org/" target="_blank">About Rails 4.</a>
        </p>
      </div>
    </div>    
  </div>  
</div>
<div class="feature feature-back">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>
          <span class="glyphicon glyphicon-fullscreen"></span>&nbsp;
          Extensible Functionality
        </h2>
        <p>
          Built upon the programmer-friendly Ruby language plus some Ruby gems, 
          it provides an extensible and maintainable framework for developing web
          applications. <a href="https://www.ruby-lang.org/" target="_blank">About Ruby 2.</a>
        </p>
      </div>
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="feature-2" title="Extensible Functionality"></div>
        </div>
      </div>
    </div>    
  </div>
</div>
<div class="feature feature-back">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="feature-3" title="Secure and Robust Application"></div>
        </div>
      </div>
      <div class="col-md-6">
        <h2>
          <span class="glyphicon glyphicon-lock"></span>&nbsp;
          Secure and Robust Application
        </h2>
        <p>
          Deployed to Heroku using SSL, SendGrid for sending e-mails, and Amazon
          Web Services for cloud storage, it is as robust as any industrial-scale
          web application should be. <a href="https://www.heroku.com/" target="_blank">About Heroku.</a>
        </p>
      </div>
    </div>
  </div>  
</div>

app/views/static_pages/_user_home_page.html.erb
<% provide(:title, current_user.name ) %>
<div class="row">
  <aside class="col-md-4">
    <!-- user info. -->
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <!-- user stats. -->
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <!-- micropost form. -->
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <!-- Feed. -->
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="row">
  <div class="col-md-12">
    <h1>About</h1>
    <p class="p_static_page">
    	This is a sample social networking site developed with Ruby 2 and Rails 4. It replaces an earlier version of <a href="http://www.twitter.com/" target="_blank">Twitter</a> with all features built from scratch.
    </p>
  </div>
</div>
<div class="feature_static_page feature-back">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="about-1" title="Features"></div>
        </div>
      </div>
      <div class="col-md-6 center features-list">
        <h2>
          <span class="glyphicon glyphicon-heart"></span>&nbsp;
          Features
        </h2>
        <ul>
          <li>User authentication (sign up and sign in forms)</li>
          <li>Form validations and alert messages</li>
          <li>User roles and authorization</li>
          <li>View and edit user profiles</li>
          <li>Show all users using pagination</li>
          <li>Update, show, and delete users</li>
          <li>Account activation and password reset</li>
          <li>Custom email messages</li>
          <li>Create and delete user microposts</li>
          <li>Upload micropost images</li>
          <li>Follow/unfollow users</li>
          <li>Status feed at user home pages</li>
        </ul>
      </div>
    </div>  
  </div>
</div>
<div class="feature feature-back">
  <div class="container">
    <div class="row row-feature">
      <div class="col-md-6 center features-list">
        <h2>
          <span class="glyphicon glyphicon-cog"></span>&nbsp;
          Technologies and languages
        </h2>
        <ul>
          <li>HTML5, CSS3, ERb and SASS</li>
          <li>Bootstrap front-end framework</li>
          <li>AJAX (plus some JavaScript functions)</li>
          <li>jQuery effects and Custom URLs</li>
          <li>RESTful resources, filters and strong parameters</li>
          <li>Input validations at client and server sides</li>
          <li>Carefully-followed MVC software architecture</li>
          <li>Well-documented Ruby code</li>
          <li>Database migrations and seeds</li>
          <li>Deployed to Heroku with SSL and SendGrid for sending e-mails</li>
          <li>Amazon Web Services for image uploading</li>
          <li>Tests for <i>all</i> features using fixtures</li>
        </ul>
      </div>
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="about-2" title="Technologies and Languages"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="row">
  <div class="col-md-12">
    <h1>Contact</h1>
    <p class="p_static_page">
      This is a sample contact page. It could contain a contact form and
      additional information about you or your business such as service hours
      and location.
    </p>
  </div>
</div>
<div class="feature_static_page feature-back">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="contact-1" title="Contact Info"></div>
        </div>
      </div>
      <div class="col-md-6 center links-list">
        <h2>
          <span class="glyphicon glyphicon-earphone"></span>&nbsp;
          Contact Info
        </h2>
        <p>
          You may reach this website's developer, Oscar Fabra, by these means:
        </p><br/>
        <ul>
          <li><%= link_to "E-mail", "mailto:oscarfabra@gmail.com", :target => "_blank" %></li>
          <li><%= link_to "Personal Website", "http://oscarfabra.com/", :target => "_blank" %></li>
          <li><%= link_to "GitHub", "http://github.com/oscarfabra", :target => "_blank" %></li>
          <li><%= link_to "Twitter", "http://www.twitter.com/oscarfabra", :target => "_blank" %></li>
          <li><%= link_to "Facebook", "http://facebook.com/oscarfabra", :target => "_blank" %></li>
          <li><%= link_to "LinkedIn", "http://linkedin.com/in/oscarfabra", :target => "_blank" %></li>
          <li><%= link_to "Google+", "http://plus.google.com/+oscarfabra", :target => "_blank" %></li>
        </ul>
      </div>
    </div>  
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="row">
  <div class="col-md-12">
    <h1>Help</h1>
    <p class="p_static_page">
      This is a sample help page. It could contain frequently asked questions 
      (FAQ's) and/or a help desk functionality. For further assistance please 
      visit the <%= link_to "Contact page", contact_path %>.
    </p>
  </div>
</div>
<div class="feature_static_page feature-back">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <div id="help-1" title="Helpful links for developers"></div>
        </div>
      </div>
      <div class="col-md-6 center links-list">
        <h2>
          <span class="glyphicon glyphicon-check"></span>&nbsp;
          Helpful links for developers
        </h2>
        <ul>
          <li><%= link_to "Ruby on Rails Guides", "http://guides.rubyonrails.org/", :target => "_blank" %></li>
          <li><%= link_to "APIdock", "http://apidock.com/", :target => "_blank" %></li>
          <li><%= link_to "Ruby doc", "http://www.ruby-doc.org/core-2.1.4/", :target => "_blank" %></li>
          <li><%= link_to "Heroku Dev Center", "https://devcenter.heroku.com/", :target => "_blank" %></li>
          <li><%= link_to "Bootstrap", "http://getbootstrap.com/", :target => "_blank" %></li>
          <li><%= link_to "Ruby on Rails Screencasts", "http://railscasts.com/", :target => "_blank" %></li>
          <li><%= link_to "Stack Overflow", "http://stackoverflow.com/", :target => "_blank" %></li>
        </ul>
      </div>
    </div>  
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <!-- Display user home page. -->
  <%= render 'static_pages/user_home_page' %>
<% else %>
  <!-- Display landing page. -->
  <%= render 'static_pages/landing_page' %>
<% end %>